// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uqgkwewalrvjmcyvvmpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZ2t3ZXdhbHJ2am1jeXZ2bXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTYxNzcsImV4cCI6MjA3OTU5MjE3N30.wbw5X43z-YHce3xsx7B0-S18bw3CrVimcNd3g3tKcMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);